# validator https://config.travis-ci.com/explore
language: c
os: linux
dist:  bionic

addons:
  apt:
    packages:
      - build-essential
      - git
      - dnsutils
      - iptables
      - iptables-persistent
      - netfilter-persistent
      - libnetfilter-queue-dev
      - libnetfilter-queue1
      - libnfnetlink-dev
      - libnfnetlink0
      - bind9
      - nghttp2
      - redis-server
      - jq

before_install:
  - bash ./tests/before_tests.sh
  - sudo bash ./tests/before_install.sh

install:
  - make
  - make dns
  - sudo make install

script:
  - sudo bash ./tests/after_install.sh
  - bash ./tests/after_tests.sh

